// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2vIx6QZ03sdYMqRVGxbFVdfdeyTUr24',
    appId: '1:695739965007:web:316bd53e38fdc9d78dd43a',
    messagingSenderId: '695739965007',
    projectId: 'fir-testingapp-1ea9f',
    authDomain: 'fir-testingapp-1ea9f.firebaseapp.com',
    storageBucket: 'fir-testingapp-1ea9f.appspot.com',
    measurementId: 'G-B21ZE76RY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2UUFHueeh5o1ybGlwAQd-wC212u4ESuo',
    appId: '1:695739965007:android:6aed3420e51d77048dd43a',
    messagingSenderId: '695739965007',
    projectId: 'fir-testingapp-1ea9f',
    storageBucket: 'fir-testingapp-1ea9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBajLtyUtPP-_tqSvpd9usTgp5YVI5076A',
    appId: '1:695739965007:ios:21e7bfd08cf82d678dd43a',
    messagingSenderId: '695739965007',
    projectId: 'fir-testingapp-1ea9f',
    storageBucket: 'fir-testingapp-1ea9f.appspot.com',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBajLtyUtPP-_tqSvpd9usTgp5YVI5076A',
    appId: '1:695739965007:ios:6a1b3d302bdef29a8dd43a',
    messagingSenderId: '695739965007',
    projectId: 'fir-testingapp-1ea9f',
    storageBucket: 'fir-testingapp-1ea9f.appspot.com',
    iosBundleId: 'com.example.hospitalApp.RunnerTests',
  );
}
